version: '3.2'
services:
  bird:
    container_name: bird
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '8050:8050'
    networks:
      - web
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      VIRTUAL_HOST: bird.backsoul.xyz
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: bird.backsoul.xyz
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com

networks:
 web:
  external: true